apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testing-space
  labels:
    app: nginx-server
    name: nginx-server
spec:
  ports:
  - name: "port-80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector: 
    app: nginx-server
    role: service
    type: ClusterIP